{
 "title": "Palindrome test",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Palindrome.js ",
   "type": "palindrome-js-panel",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "yaml_file_url",
        "type": "string",
        "values": [
         "https://gitlab.eclipse.org/eclipse-research-labs/nephele-project/vo-lwm2m/-/raw/main/TEST/D001/application-registration.yaml"
        ]
       }
      ],
      "meta": {},
      "name": "temperature-humidity"
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "yaml_file_url",
        "type": "string",
        "values": [
         "https://gitlab.eclipse.org/eclipse-research-labs/nephele-project/vo-lwm2m/-/raw/main/TEST/D003/application-registration.yaml"
        ]
       }
      ],
      "meta": {},
      "name": "layer 2"
     }
    }
   ]
  },
  {
   "title": "Palindrome.js Influxdb",
   "type": "palindrome-js-panel",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"Palindrome.js\")\n  |> range(start:-1m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_system\")\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu0\")\n  //layer: Container Metrics, ranges: [0, 3, 10]"
    },
    {
     "query": "from(bucket: \"Palindrome.js\")\n  |> range(start:-1m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\n  |> filter(fn: (r) => r[\"_field\"] == \"used\")\n  |> map(fn: (r) => ({r with _value: r._value / 1073741824}))\n  //layer: Container Metrics, ranges: [0, 16, 32]\n"
    },
    {
     "query": "from(bucket: \"Palindrome.js\")\n  |> range(start:-1m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kernel\")\n  |> filter(fn: (r) => r[\"_field\"] == \"processes_forked\")\n  |> map(fn: (r) => ({r with _value: r._value / 1000000}))\n  //layer: Container Metrics, ranges: [0, 2, 5]\n"
    },
    {
     "query": "from(bucket: \"Palindrome.js\")\n  |> range(start:-1m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\n  |> filter(fn: (r) => r[\"_field\"] == \"used\")\n  |> filter(fn: (r) => r[\"device\"] == \"mapper/ubuntu--vg-ubuntu--lv\")\n  |> filter(fn: (r) => r[\"fstype\"] == \"ext4\")\n  |> filter(fn: (r) => r[\"mode\"] == \"rw\")\n  |> filter(fn: (r) => r[\"path\"] == \"/etc/hosts\")\n  |> map(fn: (r) => ({r with _value: r._value / 1073741824}))\n  //layer: Container Metrics, ranges: [0, 75, 150]"
    },
    {
     "query": "from(bucket: \"Palindrome.js\")\n  |> range(start:-1m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"processes\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_threads\")\n  //layer: OS Metrics, ranges: [0, 75, 150]"
    },
    {
     "query": "from(bucket: \"Palindrome.js\")\n  |> range(start:-1m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"diskio\")\n  |> filter(fn: (r) => r[\"_field\"] == \"weighted_io_time\")\n  |> filter(fn: (r) => r[\"name\"] == \"dm-0\")\n  |> map(fn: (r) => ({r with _value: r._value / 1000000}))\n  //layer: OS Metrics, ranges: [0, 50, 100]"
    },
    {
     "query": "from(bucket: \"Palindrome.js\")\n  |> range(start:-1m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"diskio\")\n  |> filter(fn: (r) => r[\"_field\"] == \"write_time\")\n  |> filter(fn: (r) => r[\"name\"] == \"dm-0\")\n  |> map(fn: (r) => ({r with _value: r._value / 1000000}))\n  //layer: OS Metrics, ranges: [0, 50, 100]"
    },
    {
     "query": "from(bucket: \"Palindrome.js\")\n  |> range(start:-1m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"diskio\")\n  |> filter(fn: (r) => r[\"_field\"] == \"writes\")\n  |> filter(fn: (r) => r[\"name\"] == \"dm-0\")\n  |> map(fn: (r) => ({r with _value: r._value / 1000000}))\n  //layer: OS Metrics, ranges: [0, 50, 100]"
    },
    {
     "query": "from(bucket: \"Palindrome.js\")\n  |> range(start:-1m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_system\")\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu0\")\n  //layer: CPUs, ranges: [0, 3, 10]"
    },
    {
     "query": "from(bucket: \"Palindrome.js\")\n  |> range(start:-1m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_system\")\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu1\")\n  //layer: CPUs, ranges: [0, 3, 10]"
    },
    {
     "query": "from(bucket: \"Palindrome.js\")\n  |> range(start:-1m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_system\")\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu2\")\n  //layer: CPUs, ranges: [0, 3, 10]"
    },
    {
     "query": "from(bucket: \"Palindrome.js\")\n  |> range(start:-1m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_system\")\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu3\")\n  //layer: CPUs, ranges: [0, 3, 10]"
    },
    {
     "query": "from(bucket: \"Palindrome.js\")\n  |> range(start:-1m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_system\")\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu4\")\n  //layer: CPUs, ranges: [0, 3, 10]"
    }
   ]
  },
  {
   "title": "Palindrome.js Prometheus",
   "type": "palindrome-js-panel",
   "description": "3D monitoring",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes / 1e9 #layer: systemMetrics, ranges: [4, 16, 32]"
    },
    {
     "expr": "node_disk_io_now{device=\"nvme0n1\"} #layer: systemMetrics, ranges: [0, 50, 100]"
    },
    {
     "expr": "node_load1 #layer: systemMetrics, ranges: [0, 5, 10]"
    },
    {
     "expr": "node_disk_io_now{device=\"nvme0n1\"} #layer: serverMetrics, ranges: [0, 1000, 10000]"
    },
    {
     "expr": "node_load1 #layer: serverMetrics, ranges: [0, 5, 10]"
    },
    {
     "expr": "node_procs_running #layer: serverMetrics, ranges: [0, 5, 100]"
    },
    {
     "expr": "apache_exporter_build_info #layer: systemMetrics, ranges: [0, 2, 5]"
    }
   ]
  },
  {
   "title": "Palindrome.js Graphite",
   "type": "palindrome-js-panel",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "target": "carbon.agents.*-a.memUsage #layer: layer1, ranges: [0, 0.1, 0.2]"
    },
    {
     "target": "carbon.agents.*-a.cpuUsage #layer: layer1, ranges: [0, 0.1, 0.2]"
    },
    {
     "target": "carbon.agents.*-a.pointsPerUpdate #layer: layer2, ranges: [0, 1, 3]"
    }
   ]
  }
 ]
}