stages:
  - deploy

default:
  image: ubuntu:22.04

push-dashboard:
  stage: deploy
  before_script:
    - apt update
    - apt upgrade -y
  script:
    - apt install -y wget curl sudo zip unzip tar git cmake build-essential npm
    - wget https://go.dev/dl/go1.22.4.linux-amd64.tar.gz
    - rm -rf /usr/local/go && tar -C /usr/local -xzf go1.22.4.linux-amd64.tar.gz
    - export PATH=$PATH:/usr/local/go/bin
    - go version
    - curl --version
    - curl -sL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    - sudo apt -f install -y nodejs
    - sleep 1000000000000
    - node -v
    - cd grafonnet
    - git --version
    - git clone https://github.com/google/jsonnet.git
    - cd jsonnet
    - make
    - sudo make install
    - jsonnet --version
    - cd ..
    - go install -a github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb@latest
    - export GOPATH=$HOME/go
    - export PATH=$PATH:$GOPATH/bin
    - jb install github.com/grafana/grafonnet/gen/grafonnet-latest@main
    - cd parser
    - wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
    - export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")" [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    - nvm install 20
    - nvm use 20
    - node -v
    - npm i
    - cd ..
    - ./deploy-panel.sh
  allow_failure: false
  tags:
    - rndnode1-runner