version: '3.0'

services:
  grafana:
    container_name: 'palindrome-grafana-integration'
    platform: 'linux/amd64'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-10.0.3}
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/home.json
    volumes:
      - ./dist:/var/lib/grafana/plugins/smile-palindrome-panel
      - ./provisioning:/etc/grafana/provisioning
      - ./defaults.ini:/usr/share/grafana/conf/defaults.ini

  prometheus:
    image: prom/prometheus:v2.37.9
    user: root
    container_name: prometheus
    ports:
      - 9090:9090
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - ./prometheus-data:/prometheus
    restart: unless-stopped

  realTimeDataExporter:
    image: real-time-data-exporter
    ports:
      - 9091:9091


volumes:
  prometheus-data:
    driver: local
