version: '3.0'

services:
  grafana:
    container_name: 'palindrome-grafana-plugin'
    platform: 'linux/amd64'
    depends_on:
      - influxdb
      - prometheus
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-oss}
        grafana_version: ${GRAFANA_VERSION:-10.0.3}
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/home.json
    volumes:
      - ./dist:/var/lib/grafana/plugins/palindrome-js-panel
      - ./provisioning:/etc/grafana/provisioning

  influxdb:
    image: influxdb:2.1.1
    volumes:
      - influxdb-data:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

  telegraf:
    image: telegraf:1.19
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    depends_on:
      - influxdb
    # deploy:
    #   mode: replicated
    #   replicas: 5

  prometheus:
    image: prom/prometheus:v2.37.9
    user: root
    container_name: prometheus
    ports:
      - 9090:9090
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - ./prometheus-data:/prometheus
    restart: unless-stopped

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    ports:
      - 9100:9100
    command:
      - '--path.rootfs=/host'
    user: root
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  apache_exporter:
    image: lusotycoon/apache-exporter
    container_name: apache_exporter
    privileged: true
    ports:
    - mode: ingress
      target: 9117
      published: "9117"
      protocol: tcp
    restart: unless-stopped
    entrypoint: /bin/apache_exporter  --scrape_uri="http://172.17.0.1/server-status?auto"

  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - 8080:8080
    restart: always

  # opentsdb:
  #     image: petergrace/opentsdb-docker:latest
  #     ports:
  #         - 4242:4242
  #         - 60030:60030

volumes:
  prometheus-data:
    driver: local
  influxdb-data:
    driver: local